### ISSUE TITLE
Need to insert a record into the table post initial build of mysql

### ISSUE THREAD

**Issue by rajasekar-d** [qlik-oss/core-grpc-jdbc-connector#27]
I want to read the real time data dynamically and update the table in mysql-database 

Example:
We are not able to read the files (airports.csv if it get updated) and update the airports table in mysql-database DB.
At the time build of mysql-database if airports.csv has ten records , I can load the ten records into a mysql-database, but when my airports.csv gets updated I am not able to copy the data and push it to mysql-database.

**Comment by peol** [comment]
Hi @rajasekar-d.

If I understand you correctly, you want to insert new records into the MySQL database in our example?

In that case:
We are using the [official MySQL Docker image](https://github.com/qlik-oss/core-grpc-jdbc-connector/blob/master/example/mysql-image/Dockerfile), and are just seeding it with the airports.csv file. If you want to know how to further interact with that Docker container once it is up and running I'd suggest you read up on their documentation: https://hub.docker.com/_/mysql/

The example database is just there to get you up and running, but in a real scenario we'd expect that database to be maintained by you, and your application logic would control what is inserted/updated/deleted in the database.
