### ISSUE TITLE
loading the data on a regular frequency when qvf & qlikcore/engine is up and running.

### ISSUE THREAD

**Issue by rajasekar-d** [qlik-oss/core-grpc-jdbc-connector#28]
### Description

loading the data on a regular frequency when qvf & qlikcore/engine is up and running.

### Steps to Reproduce

1. ACCEPT_EULA=<yes/no> docker-compose up --build -d
2. npm install
3. npm start

##### Expected behavior

load the data on frequency when qvf & qlikcore/engine is up and running.

##### Actual behavior

once qvf & qlikcore/engine is up and running, we are not able to read new data and push it to qlikcore

##### Library
```
* Node.js 
* Browser
* Docker Community edition
```
##### Operating system
```
* Windows 10
```
##### Versions
```
* Node.js: v9.10.1
* Browser: 62.0.3202.62 (Official Build) (64-bit)
* Docker Community edition: 18.03.0-ce-win59 (16762)
```

**Comment by peol** [comment]
Hi. 

> once qvf & qlikcore/engine is up and running, we are not able to read new data and push it to qlikcore

Do you mean that you are creating a QVF elsewhere, and copying it into the running Qlik Core engine container while you have active sessions on it?

If so, that's not a supported use case right now. If you want to have the active sessions read in the new data you'd need to do the reload inside the engine container. Another way would be to do the reload in another container and have a shared volume between them, and then set up synchronization: https://qlikcore.com/services/qix-engine/doc-synchronization/

**Comment by rajasekar-d** [comment]
@peol thanks
Will check and update you
