### ISSUE TITLE
Update documentation regarding customization of JDBC drivers

### ISSUE THREAD

**Issue by wennmo** [qlik-oss/core-grpc-jdbc-connector#76]
The current documentation for customizing an Athena driver is not working, and the connector will not be able to resolve the driver. The problem seems to be how we declare the dependency in the `pom.xml`. Workaround is to install the jar to a local repository in the Dockerfile before running `mvn install`.

**Comment by FredrikFolkesson** [comment]
Do we know why it has worked before?

**Comment by wennmo** [comment]
Not sure, it also fails if I switch to the `athena` branch. I will sync with @peol to see if there were some additional tweaking needed.
