### ISSUE TITLE
Connection string parsing for BigQuery Simba Drivers fails.

### ISSUE THREAD

**Issue by mindspank** [qlik-oss/core-grpc-jdbc-connector#90]
Driver: BigQuery Simba 4.2 Driver
Connection string:  `CUSTOM CONNECT TO "provider=jdbc;driver=bigquery;host=https://www.googleapis.com/bigquery/v2;port=443;ProjectId=<GCloud Project>;OAuthType=0;OAuthServiceAcctEmail=<service account email>;OAuthPvtKeyPath=/secrets/bigquery.json;"`

The big query driver does not follow the jdbc://host:port/database standard and it falls through the different parsing cases we have in the code.

**Comment by peol** [comment]
Context:

We discussed just removing the connectionstring logic here: https://github.com/qlik-oss/core-grpc-jdbc-connector/blob/master/src/main/java/qlik/jdbc/connector/ConnectorImpl.java#L62 and allow the end-user (load script producer) to define the actual JDBC driver configuration in the load script instead. That way we'll be more transparent and generic, supporting a wider range of JDBC drivers.

**Comment by sublibra** [comment]
WON'T DO: Repository archived
